apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaist-frontend.fullname" . }}
spec:
  selector:
    app: {{ include "kaist-frontend.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  type: {{ .Values.service.type }}

