# kaist-ai-platform/charts/kaist-backend/values.yaml

replicaCount: 1

image:
  repository: kaist-backend
  tag: v1
  pullPolicy: Never

service:
  type: NodePort
  port: 8001      
  nodePort: 31635 

ingress:
  enabled: false
  host: your.api.domain.com
  path: /

resources: {}

config:
  SESSION_SECRET: myrandomsecretkey
  CLIENT_ID: KAIST-contest
  CLIENT_SECRET: Ke9a9rWwq3pxM0yirhkgjEn6tB4SGPGV
  REALM: KAIST
  BASE_URL: http://211.175.140.68:31635
  ISSUER_BASE_URL: https://34.171.108.238:31115/realms/KAIST
  ADMIN_ROLE: kaist-admin
  API_TOKEN: 0c3da07d93e545fca2ef613deb8c96e1
  JUPYTER_SERVER_URL: https://jupyter-kaist.duckdns.org
  JUPYTER_INTERNAL_URL: https://jupyter-kaist.duckdns.org
  DATABASE_URL: mysql+pymysql://root:devSTACK1!@34.171.108.238:31920/kaist_contest
  FRONTEND_URL: http://localhost:5173
  GCS_BUCKET: datasets-kaist
  OBJECT_STORAGE_BUCKET: datasets-kaist
  
secrets:
  OBJECT_STORAGE_ACCESS_KEY: admin
  OBJECT_STORAGE_SECRET_KEY: d4F1rocC1q0
  OBJECT_STORAGE_ENDPOINT: http://211.175.140.68:31920
  OPENAI_API_KEY: sk-

gcs:
  enabled: true
  secretName: gcs-service-account
  mountPath: /app/app/gcs-service-account.json
  
args:
  - "uvicorn"
  - "app.main:app"
  - "--host=0.0.0.0"
  - "--port=8001"
  - "--reload"  # dev mode
