# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kaist-config
  labels:
    app: kaist-backend
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
