# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kaist-secret
  labels:
    app: kaist-backend
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}

