apiVersion: v1
kind: Service
metadata:
  name: {{ include "kaist-backend.fullname" . }}
  labels:
    app: {{ include "kaist-backend.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "kaist-backend.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

